#### INSTALANDO BIBLIOTECAS

In [4]:
#INSTALÇAO DA BIBLIOTECA

!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /home/leonardoferreira/.local/lib/python3.14/site-packages (3.0.1)
Requirement already satisfied: numpy>=2.3.3 in /home/leonardoferreira/.local/lib/python3.14/site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: pip install --upgrade pip

In [5]:
import pandas as pd #importando a biblioteca pandas e dando o apelido de pd

In [6]:
print(pd.__version__) #verificando a versão da biblioteca pandas instalada

3.0.1

#### CRIANDO DATAFRAME

In [7]:
df_dados_escolas = pd.read_csv("dataset_escolas.csv") #lendo o arquivo csv e armazenando em um dataframe chamado df_dados_escolas

In [11]:
df_dados_escolas #imprimindo o dataframe df_dados_escolas para verificar se os dados foram carregados corretamente

    ID_Escola Nome_Escola Tipo_Escola  Numero_Alunos  Orcamento_Anual
0           0    Escola A     Publica           2917          1910635
1           1    Escola B     Publica           2949          1884411
2           2    Escola C  Particular           1761          1056600
3           3    Escola D     Publica           4635          3022020
4           4    Escola E  Particular           1468           917500
5           5    Escola F  Particular           2283          1319574
6           6    Escola G  Particular           1858          1081356
7           7    Escola H     Publica           4976          3124928
8           8    Escola I  Particular            427           248087
9           9    Escola J  Particular            962           585858
10         10    Escola K  Particular           1800          1049400
11         11    Escola L     Publica           3999          2547363
12         12    Escola M     Publica           4761          3094650
13         13    Escola N     Publica           2739          1763916
14         14    Escola O  Particular           1635          1043130

### FUNÇÃO PANDAS

In [12]:
#shape --> mostra a quantidade de linhas e colunas do dataframe
df_dados_escolas.shape #mostrando a quantidade de linhas e colunas do dataframe

(15, 5)

In [ ]:
##head --> mostra as primeiras linhas do dataframe
df_dados_escolas.head() #mostrando as primeiras 5 linhas do dataframe #Se quiser mostrar mais linhas use dentro do parametro o número de linhas que deseja mostrar, por exemplo: df_dados_escolas.head(10) para mostrar as primeiras 10 linhas do dataframe

   ID_Escola Nome_Escola Tipo_Escola  Numero_Alunos  Orcamento_Anual
0          0    Escola A     Publica           2917          1910635
1          1    Escola B     Publica           2949          1884411
2          2    Escola C  Particular           1761          1056600
3          3    Escola D     Publica           4635          3022020
4          4    Escola E  Particular           1468           917500

In [ ]:
#tail --> mostra as últimas linhas do dataframe
df_dados_escolas.tail() #mostrando as últimas 5 linhas do dataframe #se quiser mostrar mais linhas use dentro do parametro o número de linhas que deseja mostrar, por exemplo: df_dados_escolas.tail(10) para mostrar as últimas 10 linhas do dataframe

    ID_Escola Nome_Escola Tipo_Escola  Numero_Alunos  Orcamento_Anual
10         10    Escola K  Particular           1800          1049400
11         11    Escola L     Publica           3999          2547363
12         12    Escola M     Publica           4761          3094650
13         13    Escola N     Publica           2739          1763916
14         14    Escola O  Particular           1635          1043130

In [21]:
#info --> mostra informações sobre o dataframe, como o tipo de dados de cada coluna, a quantidade de valores não nulos, entre outras informações #Obs tatuar do braço kk
df_dados_escolas.info() #mostrando as informações do dataframe df_dados_es

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID_Escola        15 non-null     int64
 1   Nome_Escola      15 non-null     str
 2   Tipo_Escola      15 non-null     str
 3   Numero_Alunos    15 non-null     int64
 4   Orcamento_Anual  15 non-null     int64
dtypes: int64(3), str(2)
memory usage: 732.0 bytes

In [25]:
df_dados_estudantes = pd.read_csv("dataset_estudantes.csv") #

In [26]:
df_dados_estudantes

,ID_Estudante,Nome_Estudante,Genero,Serie,Nome_Escola,Nota_Redacao,Nota_Matematica
0,0,Kevin Bradley,M,6,Escola A,66,79
1,1,Paul Smith,M,9,Escola A,94,61
2,2,John Rodriguez,M,9,Escola A,90,60
3,3,Oliver Scott,M,9,Escola A,67,58
4,4,William Ray,F,6,Escola A,97,84
...,...,...,...,...,...,...,...
39155,39155,John Brooks,M,7,Escola O,92,98
39156,39156,Stephanie Contreras,F,8,Escola O,79,95
39157,39157,Kristen Gonzalez,F,6,Escola O,79,94
39158,39158,Kari Holloway,F,7,Escola O,87,90
39159,39159,Kimberly Cabrera,F,8,Escola O,85,72

In [27]:
df_dados_estudantes.info()

<class 'pandas.DataFrame'>
RangeIndex: 39160 entries, 0 to 39159
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID_Estudante     39160 non-null  int64
 1   Nome_Estudante   39160 non-null  str
 2   Genero           39160 non-null  str
 3   Serie            39160 non-null  int64
 4   Nome_Escola      39160 non-null  str
 5   Nota_Redacao     39160 non-null  int64
 6   Nota_Matematica  39160 non-null  int64
dtypes: int64(4), str(3)
memory usage: 2.1 MB

## MERGE - SE EU JUNTAR TUDO?

## ESCOLAS + ESTUDANTES

In [28]:
df_escola_estudantes = pd.merge(
    df_dados_estudantes, 
    df_dados_escolas,
    how="left", 
    on=["Nome_Escola","Nome_Escola"]
) #fazendo a junção dos dataframes df_dados_estudantes e df_dados_escolas utilizando a coluna "Nome_Escola" como chave de junção e o tipo de junção "left"

In [29]:
df_escola_estudantes

,ID_Estudante,Nome_Estudante,Genero,Serie,Nome_Escola,Nota_Redacao,Nota_Matematica,ID_Escola,Tipo_Escola,Numero_Alunos,Orcamento_Anual
0,0,Kevin Bradley,M,6,Escola A,66,79,0,Publica,2917,1910635
1,1,Paul Smith,M,9,Escola A,94,61,0,Publica,2917,1910635
2,2,John Rodriguez,M,9,Escola A,90,60,0,Publica,2917,1910635
3,3,Oliver Scott,M,9,Escola A,67,58,0,Publica,2917,1910635
4,4,William Ray,F,6,Escola A,97,84,0,Publica,2917,1910635
...,...,...,...,...,...,...,...,...,...,...,...
39155,39155,John Brooks,M,7,Escola O,92,98,14,Particular,1635,1043130
39156,39156,Stephanie Contreras,F,8,Escola O,79,95,14,Particular,1635,1043130
39157,39157,Kristen Gonzalez,F,6,Escola O,79,94,14,Particular,1635,1043130
39158,39158,Kari Holloway,F,7,Escola O,87,90,14,Particular,1635,1043130
39159,39159,Kimberly Cabrera,F,8,Escola O,85,72,14,Particular,1635,1043130

In [30]:
df_escola_estudantes.shape

(39160, 11)

In [31]:
df_escola_estudantes.info()

<class 'pandas.DataFrame'>
RangeIndex: 39160 entries, 0 to 39159
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID_Estudante     39160 non-null  int64
 1   Nome_Estudante   39160 non-null  str
 2   Genero           39160 non-null  str
 3   Serie            39160 non-null  int64
 4   Nome_Escola      39160 non-null  str
 5   Nota_Redacao     39160 non-null  int64
 6   Nota_Matematica  39160 non-null  int64
 7   ID_Escola        39160 non-null  int64
 8   Tipo_Escola      39160 non-null  str
 9   Numero_Alunos    39160 non-null  int64
 10  Orcamento_Anual  39160 non-null  int64
dtypes: int64(7), str(4)
memory usage: 3.3 MB

#### COMEÇANDO O DESAFIO

Analise os dados com base nas perguntas.

1 - Temos dados de quantas escolas?

In [34]:
total_escola = len(df_escola_estudantes["Nome_Escola"].unique())
print(f"O total de escolas únicas é: {total_escola} ")

O total de escolas únicas é: 15

2 - Qual o total de registros de estudantes na base de dados?

In [35]:
total_estudantes = df_escola_estudantes["ID_Estudante"].count() #contando a quantidade de estudantes utilizando a coluna "ID_Estudante" do dataframe df_escola_estudantes
print(f"O total de estudantes é: {total_estudantes} ")

O total de estudantes é: 39160

3 - Qual o orçamento total considerando todas as escolas?

In [40]:
#primeira solução errada
orcamento_total = (df_escola_estudantes["Orcamento_Anual"].sum()) #calculando o orçamento total utilizando a coluna "Orçamento" do dataframe df_escola_estudantes
print(f"O orçamento total é: {orcamento_total} ")

O orçamento total é: 82921898258

In [ ]:
##formatação correta do orçamento total utilizando a biblioteca locale para formatar o número como moeda brasileira

import locale

locale.setlocale(locale.LC_ALL, 'pt_BR.UTF-8')

'pt_BR.UTF-8'

In [44]:
import locale

locale.setlocale(locale.LC_ALL, 'pt_BR.UTF-8')

# Segunda SOLUÇÃO (CORRETA)
total_orcamento_unico = (
    df_escola_estudantes[['Nome_Escola', 'Orcamento_Anual']]
    .drop_duplicates()
)

total_orcamento_unico = total_orcamento_unico["Orcamento_Anual"].sum()

print(f'💰 A soma total do orçamento anual das escolas é: {locale.currency(total_orcamento_unico, grouping=True)}')

💰 A soma total do orçamento anual das escolas é: R$ 24.649.428,00

4 - Qual a média da nota dos alunos em Redação?

In [45]:
media_redacao = df_escola_estudantes["Nota_Redacao"].mean()

print(f'A média de Redação é: {media_redacao:.2f}')

A média de Redação é: 81.88

5 - Qual a média da nota dos alunos em Matemática?

In [46]:
media_matematica = df_escola_estudantes["Nota_Matematica"].mean()

print(f'A média de Matemática é: {media_matematica:.2f}')

A média de Matemática é: 78.98

6 - Considerando que a nota de aprovação é 70, quantos alunos foram aprovados em Redação? (Entegue o resultado em valor absoluto e percentual).

In [47]:
#Valor Absoluto

#Com o count precisa passar a coluna Nome Estudante

cont_estud_aprov_red = df_escola_estudantes[df_escola_estudantes["Nota_Redacao"] >= 70].count()["Nome_Estudante"]

print(f'📝 Total de estudantes aprovados em redação: {cont_estud_aprov_red}')

📝 Total de estudantes aprovados em redação: 33600

In [48]:
# Com o shape é já faço a contagem da dimensão, não preciso passar a coluna de estudante
cont_estud_aprov_red = df_escola_estudantes[df_escola_estudantes["Nota_Redacao"] >= 70].shape[0]

print(f'📝 Total de estudantes aprovados em redação: {cont_estud_aprov_red}')

📝 Total de estudantes aprovados em redação: 33600

In [49]:
##Percentual
percentual_aprov_redacao = cont_estud_aprov_red / float(total_estudantes)*100
print(f'📝 Percentual de Aprovação em Redação é: {percentual_aprov_redacao:.2f}')

📝 Percentual de Aprovação em Redação é: 85.80

7 - Considerando que a nota de aprovação é 70, quantos alunos foram aprovados em Matemática? (Entregue o resultado em valor absoluto e percentual)

In [50]:
# Com o shape é já faço a contagem da dimensão, não preciso passar a coluna de estudante
cont_estud_aprov_mat = df_escola_estudantes[df_escola_estudantes["Nota_Matematica"] >= 70].shape[0]

print(f'📝 Total de estudantes aprovados em matemática: {cont_estud_aprov_mat}')

📝 Total de estudantes aprovados em matemática: 29360

In [51]:
##Percentual

percentual_aprov_matematica = cont_estud_aprov_mat / float(total_estudantes)*100
print(f"📝 Percentual de Aprovação em Matemática é: {percentual_aprov_matematica:.2f}")

📝 Percentual de Aprovação em Matemática é: 74.97

8 - Considerando que a noa de aprovação é 70, quantos alunos foram aprovados em Matemática e Redação?
(Entregue o resultado em valor absoluto e percentual)

In [52]:
cont_aprov_total = df_escola_estudantes[(df_escola_estudantes["Nota_Matematica"] >= 70)
                                  & (df_escola_estudantes["Nota_Redacao"] >= 70)].shape[0]
print(f'📝 Total de estudantes aprovados em matemática e redação: {cont_aprov_total}')

📝 Total de estudantes aprovados em matemática e redação: 25518

In [53]:
##Percentual

percentual_aprov_total = cont_aprov_total / float(total_estudantes)*100
print(f'📝 Percentual de Aprovação em Matemática e Redação é: {percentual_aprov_total:.2f}')

📝 Percentual de Aprovação em Matemática e Redação é: 65.16

9 - Crie um dataframe com os resultados das questões de 1 a 8 que você calculou acima.

In [57]:
df_performance_escolar = pd.DataFrame({"Total de Escolas": [total_escola], 
                                       "Total de Estudantes": [total_estudantes], 
                                       "Total Orçamento": [orcamento_total],
                                       "Nota Média em Redação": [media_redacao], 
                                       "Nota Média em Matemática": [media_matematica],
                                       "% Aprovação Redação": [percentual_aprov_redacao],
                                       "% Aprovação Matemática": [percentual_aprov_matematica],
                                       "% Aprovação Total": [percentual_aprov_total]})

10 - Formate as colunas "Total de Estudantes" e "Total Orçamento" ajustando as casas decimais.

In [58]:

##SIMPLES
df_performance_escolar["Total de Estudantes"] = df_performance_escolar["Total de Estudantes"].map("{:,}".format)
df_performance_escolar["Total Orçamento"] = df_performance_escolar["Total Orçamento"].map("${:,.2f}".format)

In [59]:
##COMPLEXA
def fmt_br(valor, prefixo="", sufixo="", decimais=2):
    """Formata número no padrão brasileiro: 1.234,56"""
    valor = float(str(valor).replace(",", "").replace("$", "").strip())  # garante que é número
    formatado = f"{valor:,.{decimais}f}"
    formatado = formatado.replace(",", "|").replace(".", ",").replace("|", ".")
    return f"{prefixo}{formatado}{sufixo}"

df_performance_escolar["Total de Escolas"]        = df_performance_escolar["Total de Escolas"].map(lambda x: fmt_br(x, decimais=0))
df_performance_escolar["Total de Estudantes"]     = df_performance_escolar["Total de Estudantes"].map(lambda x: fmt_br(x, decimais=0))
df_performance_escolar["Total Orçamento"]         = df_performance_escolar["Total Orçamento"].map(lambda x: fmt_br(x, prefixo="R$ "))
df_performance_escolar["Nota Média em Redação"]   = df_performance_escolar["Nota Média em Redação"].map(lambda x: fmt_br(x))
df_performance_escolar["Nota Média em Matemática"]= df_performance_escolar["Nota Média em Matemática"].map(lambda x: fmt_br(x))
df_performance_escolar["% Aprovação Redação"]     = df_performance_escolar["% Aprovação Redação"].map(lambda x: fmt_br(x, sufixo="%"))
df_performance_escolar["% Aprovação Matemática"]  = df_performance_escolar["% Aprovação Matemática"].map(lambda x: fmt_br(x, sufixo="%"))
df_performance_escolar["% Aprovação Total"]       = df_performance_escolar["% Aprovação Total"].map(lambda x: fmt_br(x, sufixo="%"))

df_performance_escolar

,Total de Escolas,Total de Estudantes,Total Orçamento,Nota Média em Redação,Nota Média em Matemática,% Aprovação Redação,% Aprovação Matemática,% Aprovação Total
0,15,39.160,"R$ 82.921.898.258,00","81,88","78,98","85,80%","74,97%","65,16%"